const $=s=>document.querySelector(s),CHAVE="ainda_demo_7_dias_v1";
const ETAPAS=["PRIMEIRO MOMENTO — PERCEBER","SEGUNDO MOMENTO — APROFUNDAR","TERCEIRO MOMENTO — EXPERIMENTAR","QUARTO MOMENTO — CONTINUAR"];
const DADOS=[
{titulo:"Há algo que ainda importa",textos:["Antes de pensar no caminho, reconheça aquilo que ainda importa para você. Pode ser algo que deseja viver, construir, recuperar ou transformar. Não procure uma resposta perfeita. Apenas permita que uma possibilidade venha à sua mente. Por enquanto, basta reconhecer que ela existe.","Talvez você ainda não saiba explicar por que isso importa tanto. Não há problema. Algumas respostas surgem primeiro como sentimento. As palavras chegam depois, quando encontram espaço.","Em silêncio, pense: se ainda fosse possível, o que eu gostaria de não abandonar? Não tente organizar a resposta. Apenas perceba o que ela desperta em você.","Leve essa resposta com você. Os próximos motivos ajudarão a transformá-la em caminho. Algo começa a mudar quando reconhecemos o que ainda importa."]},
{titulo:"Um propósito pode começar sem forma",textos:["Talvez aquilo que importa para você ainda não tenha um nome claro. Pode ser apenas uma vontade, uma inquietação ou a sensação de que alguma coisa precisa mudar. Não tente transformar isso imediatamente em um plano. Hoje, permita que essa ideia exista sem exigir que ela esteja pronta.","Você não precisa compreender tudo para continuar. Reconhecer que deseja algo diferente já pode ser o primeiro sinal de uma nova direção.","Observe durante o dia aquilo que faz você pensar: é disso que eu gostaria de me aproximar. Pode ser um lugar, uma sensação, uma forma de viver ou uma versão de você que parecia esquecida.","Leve essa percepção com você. Não tente resolver tudo agora; algumas respostas precisam de tempo para encontrar sua forma. Amanhã haverá outro passo. Hoje pode estar transformando seu amanhã."]},
{titulo:"O que existe por trás da sua meta?",textos:["Talvez você já consiga imaginar algo que deseja alcançar: uma mudança, uma oportunidade, uma relação ou um projeto que deseja retomar. Isso é uma meta. Mas hoje olhe um pouco além dela. Pergunte o que essa conquista representaria em sua vida.","Duas pessoas podem desejar a mesma coisa por razões diferentes. A meta mostra o que você procura. O propósito começa a revelar por que isso importa.","Pense naquilo que deseja alcançar e complete mentalmente: eu quero isso porque desejo sentir, viver ou construir… Não procure uma frase bonita. Procure uma resposta verdadeira.","Talvez sua meta mude com o tempo. O caminho também poderá mudar. Leve consigo não apenas o que deseja conquistar, mas a razão pela qual vale a pena continuar."]},
{titulo:"Seu propósito não precisa ser grandioso",textos:["Um propósito também pode ser simples e profundamente verdadeiro: cuidar melhor de si, oferecer segurança a alguém, recuperar a tranquilidade ou construir uma vida da qual não precise fugir.","Se ele ajuda você a escolher uma direção, atravessar um dia difícil ou recordar quem deseja ser, já possui valor. Você não precisa impressionar ninguém com a razão que faz você continuar.","Pense por alguns instantes: o que faria minha vida parecer um pouco mais verdadeira para mim? Observe as respostas simples que normalmente passam despercebidas.","Talvez seu propósito não faça barulho. Ainda assim, pode iluminar escolhas e transformar lentamente a maneira como você vive. O que é verdadeiro não precisa ser grandioso para ser importante."]},
{titulo:"Nem todo desejo nasceu em você",textos:["Algumas metas surgem daquilo que realmente desejamos. Outras aparecem porque aprendemos que deveríamos desejá-las. Hoje, não abandone nenhuma meta. Apenas observe de onde ela veio.","Quando o esforço serve apenas para provar valor, alcançar algo talvez não traga a sensação esperada. O propósito começa quando você reconhece o que possui sentido para sua própria vida.","Pense naquilo que deseja conquistar e pergunte: eu ainda desejaria isso se ninguém estivesse olhando? Não julgue a resposta.","Você não precisa decidir nada hoje. Reconhecer a origem de um desejo já ajuda a escolher com mais liberdade. Amanhã, talvez seu caminho continue o mesmo, mas poderá pertencer um pouco mais a você."]},
{titulo:"O que você espera sentir?",textos:["Por trás de uma conquista quase sempre existe uma sensação desejada: segurança, liberdade, tranquilidade, pertencimento, orgulho ou a possibilidade de respirar com menos peso.","Talvez a meta seja apenas uma das formas possíveis de se aproximar dessa sensação. Quando reconhece o que espera sentir, você compreende melhor o propósito que orienta sua busca.","Complete mentalmente: quando isso acontecer, espero finalmente sentir… Permaneça alguns instantes com a primeira palavra que surgir.","A sensação que você procura talvez não precise esperar pela conquista inteira. Uma pequena parte dela pode começar a ser cultivada agora. Amanhã, procure onde essa possibilidade já existe em sua vida."]},
{titulo:"Talvez uma parte já esteja aqui",textos:["Hoje, observe se uma pequena parte da sensação que você procura já existe em algum lugar da sua vida.","Encontrar essa sensação agora não torna sua meta desnecessária. Apenas impede que toda a sua possibilidade de viver fique presa ao futuro.","Procure um momento, mesmo breve, em que consiga pensar: uma pequena parte daquilo que procuro já está aqui. Apenas reconheça quando acontecer.","A caminhada também acontece quando você aprende a perceber o que já está nascendo. Leve esse pequeno sinal com você. Ele mostra que o caminho já começou."]}
];
const chamadas=["Hoje pode começar de um jeito mais leve.","Uma direção pode nascer devagar.","Olhe um pouco além da meta.","O que é verdadeiro não precisa ser enorme.","Este desejo realmente pertence a você?","Há uma sensação por trás do caminho.","Talvez algo já tenha começado."];
function hoje(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function ler(){try{return JSON.parse(localStorage.getItem(CHAVE))}catch{return null}}
function salvar(v){localStorage.setItem(CHAVE,JSON.stringify(v))}
function diferenca(inicio){const a=new Date(inicio+"T12:00:00"),b=new Date(hoje()+"T12:00:00");return Math.max(0,Math.floor((b-a)/86400000))}
function tela(id){["boasVindas","encontro","espera","conclusao"].forEach(x=>$("#"+x).hidden=x!==id);scrollTo({top:0,behavior:"smooth"})}
function estadoAtual(){const e=ler();if(!e)return null;const dia=Math.min(8,diferenca(e.inicio)+1);if(e.dia!==dia){e.dia=dia;e.etapa=0;e.concluidoHoje=false;salvar(e)}return e}
function render(){const e=estadoAtual();if(!e)return tela("boasVindas");if(e.dia>7){$("#nomeFinal").textContent=e.nome;return tela("conclusao")}if(e.concluidoHoje)return mostrarEspera(e);const d=DADOS[e.dia-1],etapa=Math.min(3,e.etapa);$("#numeroDia").textContent=String(e.dia).padStart(2,"0");$("#numeroMotivo").textContent=String(e.dia).padStart(2,"0");$("#etapa").textContent=ETAPAS[etapa];$("#titulo").textContent=d.titulo;$("#texto").textContent=d.textos[etapa];$("#chamada").textContent=chamadas[e.dia-1];$("#saudacao").textContent=e.dia%2===0&&etapa===1?`QUE BOM REENCONTRAR VOCÊ, ${e.nome.toUpperCase()}`:"BOM ENCONTRO";$("#continuidade").textContent=etapa<3?["Leve esta ideia com você. Volte quando fizer sentido.","Não tenha pressa. Deixe esta reflexão amadurecer durante o dia.","Viva este gesto no seu tempo."][etapa]:"Por hoje, basta. Permita-se descansar.";$("#proximo").textContent=etapa<3?"Continuar quando fizer sentido":"Guardar este dia";$("#barra").style.width=`${((e.dia-1)*4+etapa+1)/28*100}%`;$("#rodape").textContent=`Dia ${e.dia} de 7 · momento ${etapa+1} de 4`;tela("encontro")}
function mostrarEspera(e){$("#diasVividos").textContent=e.dia;$("#mensagemEspera").textContent=`${e.nome}, leve consigo o que fez sentido. Um novo motivo será revelado amanhã.`;tela("espera")}
$("#formNome").onsubmit=ev=>{ev.preventDefault();const nome=$("#nome").value.trim();if(!nome)return;salvar({nome,inicio:hoje(),dia:1,etapa:0,concluidoHoje:false});render()};
$("#proximo").onclick=()=>{const e=estadoAtual();if(e.etapa<3)e.etapa++;else e.concluidoHoje=true;salvar(e);render()};
$("#rever").onclick=()=>{const e=estadoAtual();e.concluidoHoje=false;e.etapa=3;salvar(e);render()};render();